USE test1;

CREATE TABLE board(
BOARD_NUM INTEGER,
USER_ID   VARCHAR(50),
BOARD_WRITER   VARCHAR(20),
BOARD_SUBJECT   VARCHAR(100),
BOARD_CONTENT   VARCHAR(2000),
BOARD_boardPW   VARCHAR(200),
BOARD_COUNT   INTEGER,
IP_ADDR   VARCHAR(100),
ORIGINAL_FILE_NAME   VARCHAR(200),
STORE_FILE_NAME   VARCHAR(200),
FILE_SIZE   INTEGER,
BOARD_REGIST   TIMESTAMP(6)
);

CREATE SEQUENCE board_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
CYCLE;

SELECT NEXTVAL(board_seq);


CREATE SEQUENCE board_count
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
CYCLE;

select board_seq,USER_ID, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, BOARD_COUNT, IP_ADDR, BOARD_FILE, BOARD_REGIST
from board;


select COUNT(*) FROM board;

SELECT * FROM board;

SELECT * FROM user WHERE user_id ='wjdghk';


select * from ( select ROW_NUMBER(), board_num,USER_ID, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, BOARD_COUNT, IP_ADDR, BOARD_FILE, BOARD_REGIST
						from ( select     board_num,USER_ID, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, BOARD_COUNT, IP_ADDR, BOARD_FILE, BOARD_REGIST
								from board   WHERE board_num = ?  ))     where ROW_NUMBER() between ? and ?